//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamRole
    {
        public int ID { get; set; }
        public int EmployeeTeamID { get; set; }
        public int RoleID { get; set; }
        public bool Active { get; set; }
        public string DMLType { get; set; }
        public System.DateTime RecordInsertDateTime { get; set; }
        public string UserName { get; set; }
    
        public virtual TblEmployeeTeam TblEmployeeTeam { get; set; }
        public virtual Role Role { get; set; }
    }
}
